

server:
  port: 8080


spring:
  data:
    elasticsearch:
      #集群名称
      cluster-name: my-cluster
      #节点
      cluster-nodes: 127.0.0.1:9301,127.0.0.1:9302
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql://localhost:3306/ddd?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
